version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: timesheet
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
        PORT: ${PORT}
        UPLOADS_DIR: ${UPLOADS_DIR}
        ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
        REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
        RESET_TOKEN_SECRET: ${RESET_TOKEN_SECRET}
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      UPLOADS_DIR: ${UPLOADS_DIR}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      RESET_TOKEN_SECRET: ${RESET_TOKEN_SECRET}
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:${UPLOADS_DIR}
    depends_on:
      - db

volumes:
  db-data:
